export const champions = [
  {
    id: 'c1',
    name: 'James Mitchell',
    initials: 'JM',
    company: 'Meridian Insurance',
    role: 'Chief Technology Officer',
    stage: 'building',
    dealStatus: 'post-sfo',
    linkedinUrl: 'https://www.linkedin.com/in/james-mitchell-aviva',
    personalContact: 'null',
    lastContactDate: '2026-02-21',
    lastContactType: 'call',
    health: 'red',
    personalWins: [
      { id: 'pw1', category: 'sport', description: 'Chelsea FC season ticket holder', emoji: '⚽' },
      { id: 'pw2', category: 'ambition', description: 'Training for Ironman triathlon in 2026', emoji: '🏊' },
    ],
    professionalWins: [
      {
        id: 'prw1',
        description: 'Driving 40% reduction in claims processing time through AI automation — tied directly to our platform capabilities',
        confirmed: true,
      },
    ],
    stageCriteria: {
      'identified-building': [
        { key: 'had_1on1', label: 'Had a 1-1 conversation', met: true },
        { key: 'personal_win', label: 'Identified at least one personal win', met: true },
        { key: 'professional_win', label: 'Identified at least one professional win', met: true },
      ],
      'building-test': [
        { key: 'confirmed_prof_win', label: 'Explicitly confirmed professional win', met: true },
        { key: 'shared_internal', label: 'Shared internal context', met: true },
        { key: 'non_sales_interaction', label: 'Non-sales interaction (dinner/event/informal)', met: false },
        { key: 'personal_contact', label: 'Have personal contact (mobile/WhatsApp)', met: true },
      ],
    },
    interactions: [
      {
        id: 'i1',
        date: '2026-02-21',
        type: 'Call',
        notes: 'Quarterly review. Confirmed professional win re: claims processing reduction. Mentioned Chelsea game at weekend. Good energy.',
      },
      {
        id: 'i2',
        date: '2026-01-15',
        type: 'Email',
        notes: 'Sent article on generative AI in insurance claims. He replied positively.',
      },
      {
        id: 'i3',
        date: '2025-12-10',
        type: 'Meeting',
        notes: 'In-person at Meridian HQ. First real 1-1. Got his mobile number.',
      },
    ],
    triggers: [
      {
        id: 't1',
        type: 'sports',
        title: 'Chelsea beat Aston Villa 4-1',
        description: 'Great result last night in the Premier League',
        status: 'pending',
        createdAt: '2026-03-05',
        suggestedMessage: "James — what a result last night! Cole Palmer was absolutely unreal. Hope you caught it 🔵",
      },
    ],
    nextAction: {
      description: 'Chelsea won last night — perfect moment to send a message',
      dueDate: '2026-03-05',
      priority: 'high',
      suggestedMessage: "James — what a result last night! Cole Palmer was absolutely unreal. Hope you caught it 🔵",
    },
  },
  {
    id: 'c2',
    name: 'Sarah Clarke',
    initials: 'SC',
    company: "Pemberton Specialty",
    role: 'Chief Risk Officer',
    stage: 'identified',
    dealStatus: 'pre-sfo',
    linkedinUrl: 'https://www.linkedin.com/in/sarah-clarke-lloyds',
    personalContact: null,
    lastContactDate: '2026-02-08',
    lastContactType: 'call',
    health: 'green',
    personalWins: [
      { id: 'pw3', category: 'sport', description: 'England rugby fan — follows Six Nations closely', emoji: '🏉' },
    ],
    professionalWins: [
      {
        id: 'prw2',
        description: "Modernising risk modelling infrastructure — board pressure to reduce exposure concentration",
        confirmed: false,
      },
    ],
    stageCriteria: {
      'identified-building': [
        { key: 'had_1on1', label: 'Had a 1-1 conversation', met: true },
        { key: 'personal_win', label: 'Identified at least one personal win', met: true },
        { key: 'professional_win', label: 'Identified at least one professional win', met: false },
      ],
      'building-test': [
        { key: 'confirmed_prof_win', label: 'Explicitly confirmed professional win', met: false },
        { key: 'shared_internal', label: 'Shared internal context', met: false },
        { key: 'non_sales_interaction', label: 'Non-sales interaction (dinner/event/informal)', met: false },
        { key: 'personal_contact', label: 'Have personal contact (mobile/WhatsApp)', met: false },
      ],
    },
    interactions: [
      {
        id: 'i4',
        date: '2026-02-08',
        type: 'Call',
        notes: 'First call via intro from account team. 30 mins. Good energy. She mentioned England rugby unprompted — clearly passionate. Identified potential professional win around risk modelling.',
      },
    ],
    triggers: [
      {
        id: 't2',
        type: 'sports',
        title: 'Italy vs England — Six Nations, Sat Mar 7',
        description: 'England rugby away at Rome this Saturday',
        status: 'pending',
        createdAt: '2026-03-05',
        suggestedMessage: "Sarah — big game on Saturday! Italy away is always tricky. Fingers crossed for England 🏉",
      },
    ],
    nextAction: {
      description: 'England vs Italy rugby Saturday — good moment to connect ahead of the game',
      dueDate: '2026-03-07',
      priority: 'medium',
      suggestedMessage: "Sarah — big game on Saturday! Italy away is always tricky. Fingers crossed for England 🏉",
    },
  },
  {
    id: 'c3',
    name: 'Michael Chen',
    initials: 'MC',
    company: 'Apex General Insurance',
    role: 'Chief Operating Officer',
    stage: 'test',
    dealStatus: 'post-sfo',
    linkedinUrl: 'https://www.linkedin.com/in/michael-chen-axa',
    personalContact: 'null',
    lastContactDate: '2026-02-23',
    lastContactType: 'email',
    health: 'amber',
    personalWins: [
      { id: 'pw4', category: 'sport', description: 'Golf — member at Wentworth, plays regularly', emoji: '⛳' },
      { id: 'pw5', category: 'hobby', description: 'Fine wine collector, particularly Burgundy', emoji: '🍷' },
    ],
    professionalWins: [
      {
        id: 'prw3',
        description: "Consolidating 3 legacy ops platforms into one — under pressure to deliver by Q3 2026. Our platform is the shortlisted solution.",
        confirmed: true,
      },
    ],
    stageCriteria: {
      'identified-building': [
        { key: 'had_1on1', label: 'Had a 1-1 conversation', met: true },
        { key: 'personal_win', label: 'Identified at least one personal win', met: true },
        { key: 'professional_win', label: 'Identified at least one professional win', met: true },
      ],
      'building-test': [
        { key: 'confirmed_prof_win', label: 'Explicitly confirmed professional win', met: true },
        { key: 'shared_internal', label: 'Shared internal context', met: true },
        { key: 'non_sales_interaction', label: 'Non-sales interaction (dinner/event/informal)', met: true },
        { key: 'personal_contact', label: 'Have personal contact (mobile/WhatsApp)', met: true },
      ],
      'test-leverage': [
        { key: 'delivered_task', label: 'Delivered on a specific task', met: true },
        { key: 'shared_intel', label: 'Proactively shared competitive/deal-critical intel', met: true },
        { key: 'shown_up', label: "Shown up in a way not directly in their interest", met: false },
      ],
    },
    interactions: [
      {
        id: 'i5',
        date: '2026-02-23',
        type: 'Email',
        notes: "Forwarded competitor proposal (a legacy platform) unprompted. Massive signal — he's clearly invested in our success.",
      },
      {
        id: 'i6',
        date: '2026-02-10',
        type: 'Dinner',
        notes: 'Dinner at The Ledbury. Great evening. He opened up about Q3 board pressure. Became much more candid about internal dynamics.',
      },
      {
        id: 'i7',
        date: '2026-01-28',
        type: 'Call',
        notes: 'Deep dive on ops platform consolidation. He explicitly said "this could make or break my year."',
      },
    ],
    triggers: [],
    nextAction: {
      description: 'Follow up on competitive intel he shared — 10 days since contact',
      dueDate: '2026-03-06',
      priority: 'high',
      suggestedMessage: null,
    },
  },
  {
    id: 'c4',
    name: 'Emma Walsh',
    initials: 'EW',
    company: 'Continental Re',
    role: 'Chief Information Officer',
    stage: 'leverage',
    dealStatus: 'post-sfo',
    linkedinUrl: 'https://www.linkedin.com/in/emma-walsh-zurich',
    personalContact: 'null',
    lastContactDate: '2026-03-01',
    lastContactType: 'call',
    health: 'green',
    personalWins: [
      { id: 'pw6', category: 'sport', description: 'Tennis — plays club level, follows Wimbledon closely', emoji: '🎾' },
      { id: 'pw7', category: 'ambition', description: 'Aspires to Group CIO role — very career-driven', emoji: '🎯' },
    ],
    professionalWins: [
      {
        id: 'prw4',
        description: "First major tech transformation under her leadership — career-defining. Success = Group CIO path opens.",
        confirmed: true,
      },
    ],
    stageCriteria: {
      'identified-building': [
        { key: 'had_1on1', label: 'Had a 1-1 conversation', met: true },
        { key: 'personal_win', label: 'Identified at least one personal win', met: true },
        { key: 'professional_win', label: 'Identified at least one professional win', met: true },
      ],
      'building-test': [
        { key: 'confirmed_prof_win', label: 'Explicitly confirmed professional win', met: true },
        { key: 'shared_internal', label: 'Shared internal context', met: true },
        { key: 'non_sales_interaction', label: 'Non-sales interaction (dinner/event/informal)', met: true },
        { key: 'personal_contact', label: 'Have personal contact (mobile/WhatsApp)', met: true },
      ],
      'test-leverage': [
        { key: 'delivered_task', label: 'Delivered on a specific task', met: true },
        { key: 'shared_intel', label: 'Proactively shared competitive/deal-critical intel', met: true },
        { key: 'shown_up', label: "Shown up in a way not directly in their interest", met: true },
      ],
      'leverage': [
        { key: 'influencing_internal', label: 'Influencing internal discussions without Rich present', met: true },
        { key: 'deal_acceleration', label: 'Connected to deal acceleration', met: true },
        { key: 'personal_maintenance', label: 'Active personal win maintenance ongoing', met: false },
        { key: 'expansion_signals', label: 'Identifying expansion/new opportunity signals', met: false },
      ],
    },
    interactions: [
      {
        id: 'i8',
        date: '2026-03-01',
        type: 'Call',
        notes: 'She ran the internal steering committee and pushed our solution through without being asked. Deal should close this month.',
      },
      {
        id: 'i9',
        date: '2026-02-14',
        type: 'Gift',
        notes: 'Sent Wimbledon debenture tickets for this summer as a relationship gesture. She was genuinely thrilled.',
      },
      {
        id: 'i10',
        date: '2026-02-05',
        type: 'Call',
        notes: 'She shared the internal decision timeline and who the holdouts were. Completely trust-based relationship now.',
      },
    ],
    triggers: [],
    nextAction: {
      description: 'Send personal thank-you — she went above and beyond last week',
      dueDate: '2026-03-05',
      priority: 'high',
      suggestedMessage: "Emma — just wanted to say a genuine thank you for last week. You didn't have to go that extra mile and it means a lot. Let's celebrate properly when we get this over the line.",
    },
  },
  {
    id: 'c5',
    name: 'David Patel',
    initials: 'DP',
    company: 'Atlas Assurance',
    role: 'Chief Data Officer',
    stage: 'building',
    dealStatus: 'pre-sfo',
    linkedinUrl: 'https://www.linkedin.com/in/david-patel-allianz',
    personalContact: null,
    lastContactDate: '2026-02-15',
    lastContactType: 'call',
    health: 'amber',
    personalWins: [
      { id: 'pw8', category: 'sport', description: 'India cricket — huge fan, follows every series', emoji: '🏏' },
      { id: 'pw9', category: 'ambition', description: 'Building a data science capability from scratch — his legacy project at Atlas Assurance', emoji: '📊' },
    ],
    professionalWins: [
      {
        id: 'prw5',
        description: "Modernising data governance and analytics infrastructure — our platform provides the data layer he needs for his team's capabilities",
        confirmed: false,
      },
    ],
    stageCriteria: {
      'identified-building': [
        { key: 'had_1on1', label: 'Had a 1-1 conversation', met: true },
        { key: 'personal_win', label: 'Identified at least one personal win', met: true },
        { key: 'professional_win', label: 'Identified at least one professional win', met: true },
      ],
      'building-test': [
        { key: 'confirmed_prof_win', label: 'Explicitly confirmed professional win', met: false },
        { key: 'shared_internal', label: 'Shared internal context', met: false },
        { key: 'non_sales_interaction', label: 'Non-sales interaction (dinner/event/informal)', met: false },
        { key: 'personal_contact', label: 'Have personal contact (mobile/WhatsApp)', met: false },
      ],
    },
    interactions: [
      {
        id: 'i11',
        date: '2026-02-15',
        type: 'Call',
        notes: 'Second call. Opened up more. Confirmed data governance ambitions. Mentioned India cricket unprompted — clearly a real passion.',
      },
      {
        id: 'i12',
        date: '2026-01-22',
        type: 'Call',
        notes: 'Intro call via LinkedIn. 45 minutes. Good vibes. Broad discussion on data modernisation.',
      },
    ],
    triggers: [],
    nextAction: {
      description: 'India vs England Test series coming up — good opportunity to connect',
      dueDate: '2026-03-12',
      priority: 'medium',
      suggestedMessage: null,
    },
  },
]

export const actionQueue = [
  {
    id: 'a1',
    type: 'overdue',
    priority: 'high',
    championId: 'c1',
    championName: 'James Mitchell',
    company: 'Meridian Insurance',
    stage: 'building',
    description: '12 days since last contact — overdue on 2-week cadence',
    suggestedAction: 'Chelsea beat Aston Villa 4-1 last night — perfect moment to message',
    suggestedMessage: "James — what a result last night! Cole Palmer was absolutely unreal. Hope you caught it 🔵",
  },
  {
    id: 'a2',
    type: 'trigger',
    priority: 'high',
    championId: 'c4',
    championName: 'Emma Walsh',
    company: 'Continental Re',
    stage: 'leverage',
    description: 'Personal: send a thank-you for going above and beyond last week',
    suggestedAction: 'Send a personal thank-you message today',
    suggestedMessage: "Emma — just wanted to say a genuine thank you for last week. You didn't have to go that extra mile and it means a lot. Let's celebrate properly when we get this over the line.",
  },
  {
    id: 'a3',
    type: 'approaching',
    priority: 'medium',
    championId: 'c3',
    championName: 'Michael Chen',
    company: 'Apex General Insurance',
    stage: 'test',
    description: '10 days since last contact — approaching 2-week cadence deadline',
    suggestedAction: 'Follow up on the competitive intel he shared — show appreciation',
    suggestedMessage: null,
  },
  {
    id: 'a4',
    type: 'sports',
    priority: 'medium',
    championId: 'c2',
    championName: 'Sarah Clarke',
    company: "Pemberton Specialty",
    stage: 'identified',
    description: 'England vs Italy — Six Nations rugby, Saturday Mar 7',
    suggestedAction: 'Message ahead of the game to build rapport',
    suggestedMessage: "Sarah — big game on Saturday! Italy away is always tricky. Fingers crossed for England 🏉",
  },
]
